# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: TerraformAgent
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure CLI'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az login'
- task: TerraformCLI@0
  displayName: Terraform init
  inputs:
    command: 'init'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  displayName: Terraform plan
  inputs:
    command: 'plan'
    environmentServiceName: 'activ-edge(a17a081a-c3f6-4fce-a0fd-6bef7752f473)'
    allowTelemetryCollection: false
- task: TerraformCLI@0
  displayName: Terraform apply
  inputs:
    command: 'apply'
    environmentServiceName: 'activ-edge(a17a081a-c3f6-4fce-a0fd-6bef7752f473)'
    allowTelemetryCollection: false



